domeengine/dome

main.wren
src/engine.c
src/engine/dome.c
src/engine/dome.wren
src/engine/modules.c
src/main.c
src/util/generateEmbedModules.sh
src/vm.c

Implements request #5 
There is now a DOME module which can contain DOME-centric configuration
methods and properties. It also adds an `exit` method which can be used
by a game to exit the execution.
~~A caveat to this is that you can't quit a VM from within the C code,
so we need to wait for the execution to reach the core engine loop
before we can safely shutdown the Wren VM.~~
EDIT: We can use setjmp/longjmp to bypass the WrenVM execution and execute the DOME shutdown sequence, which cleans up memory safely.

Introduce a DOME module and an exit function

---

docs/modules/audio.md
src/modules/audio.c

This fixes #2 by making the audio channel list resizable.
We also moved to using the SDL callback which pushes mixing into a separate thread, so that audio won't be blocked by the game processing update loop.

Audio Engine Improvements

---

Makefile
README.md
docs/modules/io.md
main.wren
src/audio_types.c
src/debug.c
src/engine.c
src/io.c
src/main.c
src/modules/audio.c
src/modules/audio.wren
src/modules/graphics.wren
src/modules/io.c
src/modules/io.wren
src/vm.c

This PR breaks the old API a little bit, by  moving `load` to `loadAsync` and instead, `load` is now `loadSync`.
If you use `loadSync` or `saveSync`, you'll be given a warning message.
It also introduces a way to write to files,`save(path, stringBuffer)` which will create and overwrite files.
Other changes:
DOME has a `debug` mode now, enabled by the `-d` or `--debug` flag. This is intended for DOME development, and enables slightly deeper stack traces when errors occur inside DOME built-in methods. The features toggled by this mode can be expanded over time.

File API Changes

---

src/engine.c
src/io.c
src/main.c

If you tried to install dome onto the user bin path, or wanted to symlink DOME for VCS purposes (see #31 ) you'd find problems as DOME used the location of it's executable, rather than the current working directory.
NOTE: This probably breaks application bundles for OS X at the moment. We need to detect if we are in a bundle and then use that location.

We use the current working directory for the base path

---

src/main.c
src/modules/audio.c
src/modules/audio.wren
src/modules/io.c
src/modules/io.wren
src/vm.c

Based on how the Wren CLI captures variables, we lazy-load the audioEngine and DataBuffer classes as they are loaded

Lazy-capture AudioEngine and DataBuffer classes

---

docs/modules/graphics.md
examples/spaceshooter/main.wren
src/math.c
src/modules/graphics.wren
src/modules/image.c
src/modules/image.wren
src/util/generateEmbedModules.sh
src/vm.c

After a lot of back and forth, this is the least-error-prone approach to rotation/scaling:
- Rotation can only happen at 90 degree increments.
- Negative scaling is equivalent to flipping.
- Flipping occurs after rotation.
- Images are rotated and fixed to the top-left corner, so they should appear to rotate "in place", if the image is square.

Simple rotate and scale

---

examples/spaceshooter/main.wren
src/engine.c
src/engine.h
src/main.c
src/modules/graphics.wren
src/modules/image.c

The current gif recording system (`--record=gifName.gif`) is rather intensive on the main thread, so this PR offloads the file IO and pixel-channel-rearrangement to its own thread.
Unfortunately, it still struggles to keep a good frame-rate, depending on the size of the canvas and number of colours in use, so I don't recommend it for serious work.

Gif record

---

docs/modules/audio.md
src/modules/audio.c
src/modules/audio.wren
src/vm.c

During DOMEjam, I added this so you can start an audio channel at a sample position (useful for Rhythm Game Level Editing).

Set Audio Channel position

---

docs/modules/dome.md
src/modules/dome.c
src/modules/dome.wren
src/vm.c

For completeness.
In dome.c
```c
internal void
WINDOW_getWidth(WrenVM* vm) {
ENGINE* engine = (ENGINE*)wrenGetUserData(vm);
int width = 0;
SDL_GetWindowSize(engine->window, &width, NULL);
wrenSetSlotDouble(vm, 0, width);
}
internal void
WINDOW_getHeight(WrenVM* vm) {
ENGINE* engine = (ENGINE*)wrenGetUserData(vm);
int height = 0;
SDL_GetWindowSize(engine->window, NULL, &height);
wrenSetSlotDouble(vm, 0, height);
}
```
Example code
```js
System.print("%(Window.width) %(Window.height)")
```

Added properties Window.width and Window.height

---

docs/modules/dome.md
src/modules/dome.c
src/modules/dome.wren
src/vm.c

Inspired by the work in [#59]
Provides a simple interface for testing the version of DOME being used, although it doesn't support additional labels in the `semver` format. (Eg: `1.2.0-dev`).

Version Module

---

Makefile
setup_wren.sh

Wren 0.3.0 made significant changes to its build system, so the DOME build process needed tweaking.
This exposes a certain amount of fragility in the system, so future work should be invested in streamlining the build process.
However, this is sufficient.
Among other changes, this adds an ARCH flag to the make script which can be either `32bit` or `64bit`, in order to build the correct version of `libwren.a`

Upgrade to Wren 0.3.0

---

.gitignore
docs/modules/input.md
examples/spaceshooter/main.wren
setup_static_mac_sdl.sh
setup_wren.sh
src/engine.c
src/engine.h
src/include/microtar/microtar.c
src/include/microtar/scenario-target-travel-ifa.pdf
src/main.c
src/modules/dome.c
src/modules/dome.wren
src/modules/input.c
src/modules/input.wren
src/vm.c

I've frequently found myself wanting to track if a digital input (keyboard, mouse or gamepad button) has _just_ been pressed, or has been held for a long time. Rather than relying on a library that I've ended up porting from project to project, I've pulled much of the buffering functions into the core library.
The architecture for handling these inputs has changed somewhere, as we now "push" the button state to the game when something changes.
As a bonus, I've also implemented a "Relative Mode" for the mouse, which allows for mouse-lock navigation that is common in FPS-style games, just in case.
NOTE: During this PR, I discovered that SDL2 2.0.2 doesn't correctly handle GamePads on Catalina, so I've upgraded to 2.0.6 going forward.

Double-Buffering Inputs and Mouse-Lock

---

docs/modules/input.md
src/modules/input.wren

`DigitalInput.justPressed` for convenience and Keyboard.`isButtonPressed(key)` for consistency.

DigitalInput Quality of Life Changes

---

src/main.c

addresses #91 
added
```c
ENGINE_printLog(engine, "Wren version: %d.%d.%d\n", WREN_VERSION_MAJOR, WREN_VERSION_MINOR, WREN_VERSION_PATCH);
```
to [main.c](https://github.com/avivbeeri/dome/blob/master/src/main.c#L147)

added wren version

---

README.md
docs/modules/io.md
src/include/mkdirp/mkdirp.c
src/include/mkdirp/mkdirp.h
src/io.c
src/main.c
src/modules/io.c
src/modules/io.wren
src/vm.c

Simulates `mkdir -p` and aborts if directory couldn't be created. Testing done on linux (Ubuntu 18.04). Windows tests are needed.
Fixes #102 
Uses code from [mkdirp](https://github.com/stephenmathieson/mkdirp.c)
Example usage:
```
import "io" for FileSystem
FileSystem.createDirectory("test/me/out")
```
The permissions given to the directory are hard coded to `0777` as of now which should be changed if required.
Do let me know of any changes!

Added createDirectory functionality

---

docs/modules/dome.md
src/engine.c
src/engine.h
src/main.c
src/modules/color.wren
src/modules/dome.c
src/modules/dome.wren
src/modules/graphics.wren
src/modules/image.wren
src/vm.c

This is my take on #87 and #89 , inspired by how NodeJS handles its commandline parameters.
The resulting usage now looks like this:
```
Usage:
dome [options]
dome [options] [--] entry_path [arguments]
dome -h | --help
dome -v | --version
```
The first case, where no arguments are provided, will follow the established auto-resolution procedure:
1) Is there `game.egg` in the current working directory? if so, execute it
2) Is there `main.wren` in the current working directory? if so, execute it.
3) Print an error, since no entry point could be found.
For the second case, where an entry path (the first non-option argument) and some number of arguments are provided, will do the following:
1) Is the entry path a directory? If so, follow the auto-resolution as described above, using that …

Process Arguments

---

docs/modules/json.md
src/modules/json.wren

When passing a custom class the encoder would fail
since it would return null.
This invokes the `toString` method in the object as the default encoding.

added missing encoding use case

---

docs/modules/graphics.md
src/modules/image.c
src/modules/image.wren

Allows the `transform` method to set an image's opacity globally, to allow fading-style effects.

Image opacity property

---

src/modules/math.wren

And thus the previous expression was equal to `(!n) is Num`, which is obviously incorrect 😄

Hmm... `is` has lower precedence than `!`

---

src/modules/vector.wren

It is more performant, which is important when we create a lot of vectors, which is common in games, especially if you remember that every operation on vector creates a new vector.
It is also nicer (IMHO), and would allow us to use short field representation if https://github.com/wren-lang/wren/issues/849 will be accepted.
The reasons it's more performant:
- Lists have a backing storage, which is storage separately, meaning more memory + more GC + more indirection. All affect performance, and not for good.
- Lists must do bounds checking every time we access an element. Fields don't.
- **Edit:** Lists also call methods in order to access the element (`[_]`). We already have a method call for accessing each field, as we access their getters and not directly the fields. We can access the …

Represent vector using four fields and not one list

---

src/engine.c
src/main.c

Key loop state is now managed as a struct and passed between methods representing phases of the game loop.
This allows for a reduced code duplication and a clearer structure for the game loop.
It also fixes some behaviour around input handling during "catchup" and strange behaviour using the lockstep setting.

Break down game loop into discrete functions

---

src/vm.c

We are using the Wren 0.4.0 pre-release tag because there is not expected to be any code changes between it and the official release tag. See the change list here: https://github.com/wren-lang/wren/releases/tag/0.4.0-pre
It also brings a number of bug-fixes which will improve the overall stability and robustness of DOME, as well as a few API improvements and some expanded functionality which can be made use of by all games moving forward.

Update Wren to 0.4.0-pre

---

src/modules/color.wren

This is more performant (and common colors are used commonly), and saves less space because of extra hashmap entries (although this is just one instance for the entire program)
This is also more idiomatic, IMHO, because you don't need a map but a fixed set of colors

Use global variables for common colors instead of map

---

src/modules/color.wren

```wren
method() {
return xyz
}
```
into
```wren
method() { xyz }
```

Replace one-line methods with implicit return

---

docs/modules/json.md
src/modules/json.wren

With an option to disable the check: `JsonOptions.checkCircular`.
The check is not complete because we can't check custom objects that override `.toString`, but this is the best we can.
Fixes #141.

Reject circular JSON

---

docs/modules/audio.md
examples/audio/main.wren
src/main.c
src/math.c
src/modules/audio.c
src/modules/audio.wren
src/modules/map.c
src/vm.c

This PR does a few things around the audio engine:
1) Creates a GenericChannel which can be played by the audio engine. This is necessary so that C-side code can easily output arbitrary sound data.
2) The AudioChannel now implements the GenericChannel "interface", and most of the "AudioChannelFacade" functions (including the state machine) have now been pushed from the Wren layer to the C layer.
3) We now have the ability to run a rudimentary resampling algorithm over incoming audio data. This means we can accept data using any sample rate, although CD quality audio is still recommended. Resampling is performed during file load, and is very slow. This is a good candidate for asynchronous operations in the future.

Audio Engine re-architecting (pt1) + resampling

---

src/main.c

Allow external programs to get better visibility on the debug output by preventing buffering.

Disable stdout/stderr buffers

---

examples/plugin/test.c

`ExternalClass` should be foreign

---

docs/modules/graphics.md
src/engine.c
src/modules/font.c

This adds newline support in for Canvas.print(). A default spacing of `fontHeight / 4` has been set. The user should probably be able to customize this at some point.

Newline support for fonts

---

docs/plugins/index.md
include/dome.h
src/plugin.c

`wrenSetSlotNewForeign()` cannot be used for something other than foreign allocator if they are not provided.

Provide access to `wrenGetVariable()` and `wrenGetSlotHandle()`

---

docs/plugins/index.md
include/dome.h
src/plugin.c

As per [#176], this adds the last methods from Wren which may be useful for plugins in standard implementation.

Final Wren API methods

---

docs/modules/graphics.md
examples/fonts/main.wren
src/modules/font.c
src/modules/font.wren
src/modules/graphics.wren
src/util/wrenembed.c
src/vm.c

`RasterisedFont.getArea` and `Canvas.getPrintArea` allow access to the font draw size, for figuring out wrapping and justification of text.

TTF Font Area Calculation

---

src/modules/image.c
src/modules/image.wren

DrawTransform was created before maps were available from the slot API. This swaps out the list-mechanism for the new Map methods, which should reduce the required memory allocations of more graphically intensive code.

DrawTransformOptimisation

---

Makefile
include/glibc_compat.c
include/vendor.c

Follows the instructions from [#189] to make linux builds backwards compatible, even if compiled against newer versions of GLIBC (At least for now)

Glibc compatibility

---

docs/modules/graphics.md
src/modules/graphics.wren

This makes it possible to do `Canvas.font` to get the current font name as a string.

Added Canvas.font getter

---

AUTHORS.md
docs/modules/math.md
src/modules/math.wren

This pull updates the Dome Math library to use the inbuilt functions for min, max and clamp., The changed functions are 
- Math.min (a, b)
- Math.max(a, b)
- Math.mid (a, b, c)
Also, a new function Math.clamp (number, min, max ) has been added which is a wrapper around the inbuilt Num.clamp function

Updated the math library to use inbuilt functions

---

src/modules/graphics.c

When setting the clip region, we didn't guard against the clip region overflowing the canvas buffer correctly. This corrects the issue.

Clip Crash Fix

---

src/modules/graphics.c

Quick fix for a bug found on stream.

Clip zone now respects the edge of the screen so we don't accidentally underflow.

---

src/vm.c

This is to get around some issues with module path resolution, but internal modules can shadow external ones.

We warn the developer if an import path matches internal module

---

AUTHORS.md
docs/modules/io.md
src/engine.c
src/io.c
src/modules/io.c
src/modules/io.wren
src/vm.c

I saw in the discord server someone was asking about this and though it was A simple enough feature to implement. So I did. The new method is called fileExists in the class FileSystem. It returns true if the file exists and false it not.

Add method to FileSystem to check for file existance

---

examples/circle/main.wren

I know this is the smallest of changes, but I was looking through the example and got an unexpected crash due to the circle's size being negative.
So I thought I would go ahead and create a PR to fix that.

Fixes a bug in the circle example

---

src/modules/collections.wren

Adding the contents of one iterable into another is really handy so we should probably support that, where it makes sense.

Collections sometimes support addall now

---

AUTHORS.md
src/main.c

Fixing windows terminal support as well as powershell and cmd support since they weren't outputing anything either.

Fix windows terminal support

---

src/engine.c
src/game.c
src/main.c

What does this PR do?
- Adds cli flag to dome executable to control screen that it opens to
Usage 
`dome -s 1` opens dome on second screen

Add cli flag to choose screen window is opened on
