Makefile
main.wren
src/debug.c
src/engine.c
src/io.c
src/main.c
src/modules/audio.c
src/modules/point.wren
src/vm.c

Small tweaks to marginally improve performance, as well as fixing the draw-interpolation feature of the game loop

Performance

---

.gitmodules
Makefile
README.md
docs/modules/input.md
main.wren
src/engine.c
src/main.c
src/modules/input.c
src/modules/input.wren
src/strings.c
src/vm.c

Adds Mouse and Controller support

Additional Input Methods - Mouse and Controllers

---

README.md
docs/index.md
docs/modules/dome.md
docs/modules/graphics.md
docs/modules/index.md
main.wren
src/engine.c
src/main.c
src/modules/dome.c
src/modules/dome.wren
src/modules/graphics.c
src/modules/graphics.wren
src/vm.c

Implements #12 as well as allowing the window to be resized.

Canvas resiziing

---

Makefile
README.md
src/engine.c
src/include/optparse.h
src/main.c
src/modules/audio.c

This tackles  #13 by introducing optparse.h: https://github.com/skeeto/optparse
This lets us do both short and long parameters and flags/switches.
We also simplify the dual wren/egg file selection.

Better command line parameter parsing

---

src/debug.c
src/main.c
src/modules/audio.c
src/modules/dome.c
src/modules/ffi.c
src/modules/graphics.c
src/modules/image.c
src/modules/input.c
src/modules/io.c
src/vm.c

Adds an assertion for mismatched internal module calls, so the user knows when an error is made.

Error asserts

---

examples/spaceshooter/main.wren
src/engine.c
src/engine.h
src/main.c
src/modules/graphics.wren
src/modules/image.c
src/modules/image.wren
src/vm.c

Circles and Ellipsis were not drawing correctly if the color was transparent.

Geometry Alpha Fixes

---

README.md
docs/modules/io.md
src/engine.c
src/include/tinydir.h
src/main.c
src/modules/io.c
src/modules/io.wren
src/vm.c

This requires cross-platform checks

Directory reading

---

Makefile
setup_wren.sh
src/engine.c
src/io.c
src/main.c
src/vm.c

- Priorize builtin modules over files
- Fix loading from game.egg
- Fix loading resources from macOS app bundle
- `./` on custom modules is optional

Improve importing modules

---

src/engine.c
src/main.c

To improve the experience of developing on Windows, this PR makes sure we flush the file buffer when writing the log file, so it can be examined on a line-by-line basis.

Windows Console Handling

---

.gitignore
docs/modules/graphics.md
src/modules/graphics.wren
src/modules/image.c
src/modules/image.wren
src/modules/math.wren
src/vm.c

Very simply, provides `ImageData.pget` which can be used to retrieve the color value of a pixel in ImageData. This would be useful for some side projects, where the image loaded in isn't directly blitted to the display, but is instead used for other purposes.
This also changes the `toString` of the Color class to be more human-readable.

implemented ImageData.pget, which is useful for 3D texture rendering

---

.gitignore

This file is automatically created when doing make on macos.

added .arch to gitignore

---

docs/modules/input.md
src/modules/input.wren
src/util/embed.c

This also includes a change to the Wren script embedder, in order to eliminate string length warnings.

Added allPressed and reset options to the input module

---

docs/modules/dome.md
src/main.c
src/modules/dome.c
src/modules/dome.wren
src/vm.c

added Window.fps

---

src/main.c

The initial bug: An error occurring during the WrenInterpret phase, when the user code has acquired some WrenHandles already, would lead to these not being freed during cleanup, resulting in an error report on some systems.
To fix this, the interpreter's failure GOTO for this phase was changed from `cleanup` to `vm_cleanup`, and correct error handling is added.
This will (close #101)

Handle release bug fix

---

docs/modules/input.md
examples/spaceshooter/main.wren
src/engine.c
src/engine.h
src/main.c
src/modules/input.c
src/modules/input.wren
src/modules/math.wren
src/vm.c

I find myself often wanting Mouse co-ordinates as a vector, so this is a convenience method for supplying that.

Mouse Position and Scroll vectors

---

.editorconfig
.gitattributes

Standarize editor configuration.

Added editorconfig and gitattributes

---

.github/workflows/build-all.yml

Upstream image changes swapped from XCode 11 to XCode 12, breaking our script.

Fixing mac os build

---

CONTRIBUTING.md
docs/modules/json.md
src/modules/json.c
src/modules/json.wren

changed constant convention to follow _Wren's_ convention

changed constants conventions

---

Makefile
docs/modules/graphics.md
examples/clipping/main.wren
src/engine.c
src/engine.h
src/main.c
src/modules/graphics.c
src/modules/graphics.wren
src/vm.c

Allow the definition of a clipping region for more advanced UI drawing and other fancy graphics tasks.
There's some initial refactoring here to decouple the Canvas from the engine core.

Canvas.clip

---

docs/modules/json.md

Namely, missing spaces and incorrect heading

Fix some docs issues

---

src/modules/color.wren
src/modules/vector.wren

For various reasons, it makes sense to be able to treat Color as a Vector object.
In addition, this makes subclassing Vector easier by handling the operators in a more generic fashion.

Color re-implemented as a subclass of Vector

---

src/modules/vector.wren

You don't have to merge this PR, but it's more Wren-iq IMHO.

Replace `this.type` with `type`

---

docs/modules/dome.md
scripts/generateEmbedModules.sh
src/main.c
src/modules/dome.wren
src/modules/platform.c
src/modules/platform.wren
src/vm.c

There are occasionally reasons where it is useful to know the current system time and OS type, so this provides that information.

Basic Platform Module

---

docs/modules/dome.md
scripts/generateEmbedModules.sh
src/engine.c
src/main.c
src/modules/color.wren
src/modules/dome.c
src/modules/dome.wren
src/modules/graphics.wren
src/modules/image.wren
src/modules/input.wren
src/modules/stringUtils.wren
src/vm.c

This property gets and sets the background color beyond canvas boundaries.

Add property `Window.color`

---

scripts/setup_wren.sh

added double quote to prevent crashes.

fixed crash when path contains whitespace

---

src/util/embed.c
src/util/wren2cstring.c

Embed refactoring

---

README.md
docs/getting-started.md
docs/plugins/example.md
examples/alpha/main.wren
examples/audio/main.wren
examples/clipping/main.wren
examples/empty/main.wren
examples/fonts/main.wren
examples/geometry/main.wren
examples/plugin/main.wren
examples/random/main.wren
examples/rect/main.wren
examples/spaceshooter/main.wren

Remove use of static fields in examples

---

docs/plugins/index.md

Embed command docs

---

README.md

Oops, should have spotted this one too in my earlier PR.

In README.md class is still called Game.

---

docs/modules/input.md
examples/textInput/main.wren
src/engine.c
src/engine.h
src/main.c
src/modules/dome.c
src/modules/input.c
src/modules/input.wren
src/vm.c

Allows users to enter full strings of text for various purposes.
Resolves the root problem expressed by #186

Text Input

---

docs/modules/graphics.md
src/modules/graphics.c
src/modules/graphics.wren
src/vm.c

This pulls adds 
- Canvas.offsetX - returns X offset
- Canvas.offsetY - returns Y offset
- Canvas.offset getter - returns Vector of offset X and offset Y
- Canvas.offset setter - sets Canvas offset
Closes #187

Added Offset Getters and Setters

---

src/engine.c
src/engine.h
src/game.c
src/main.c
src/tools/fuse.c

No functional changes, but I did a few code transformations which have been bugging me for a while, which I hope will make it easier to work on things in the future.
This does enforce that fused binaries can't be used as standard DOME binaries, though.

Entry point refactoring

---

.gitignore
.gitmodules
Makefile
include/wren.c
include/wren.h
scripts/setup_wren_web.sh

@avivbeeri  #219
>I think the proper approach for this is to swap to using Wren's amalgamated build. We should commit a version of it to the repo, and then we can re-generate it when Wren releases a new version. This can then be built into its own module (similar to the vendor module), and linked in.
This pr also disables using the glibc_compat on arm64 linux as the build currently fails without doing that. This is a temporary workaround until a better solution is found.

Use amalgamated build of wren for wider range of device compatibility

---

Makefile
src/engine.c
src/game.c
src/io.c
src/main.c
src/modules/graphics.c
src/tools/embed.c
src/tools/nest.c

Simple bug-fixes for the clip region issue and loading of absolute paths.

Release Branch: 1.7.1

---

AUTHORS.md
docs/modules/graphics.md
src/modules/graphics.c
src/modules/graphics.wren
src/vm.c

Clip getter

---

docs/modules/input.md
src/modules/input.wren

This still requires documentation, but it's essentially the same input group I've used in Parcel for a couple years.

Added InputGroup for enhanced input handling

---

docs/modules/graphics.md
src/modules/graphics.wren
src/modules/image.c
src/modules/image.wren
src/vm.c

This is a simplified version of Parcel's tilesheet with documentation.

Implementing a simple Spritesheet class

---

.github/workflows/build-all.yml
.github/workflows/itch.yml
Makefile
scripts/setup_static_mac_sdl.sh

* universal binary support
* update action workflow
Fixes #253

Universal Mac OS Binary (#254)
